<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<div class="cart secondary actions">
    <button type="button"
            name="cart_export"
            value="cart_export"
            title="<?= $block->escapeHtml(__('Download Cart CSV')); ?>"
            class="action export" id="cart_export_button"
            onclick="window.location = '<?= $block->escapeUrl($block->getUrl('cart_export')); ?>';">
        <span><?= $block->escapeHtml(__('Download Cart CSV')); ?></span>
    </button>
</div>